steal()
.then(function() { TODOLIB = 'jquery'; })
.then('test.js?jquery')
.then(function() { TODOLIB = 'yui'; })
.then('test.js?yui')
.then(function() { TODOLIB = 'yui-widget'; })
.then('test.js?yui-widget')